---
title: "Jackknife"
author: "L Kell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: word_document
---

```{r, eval=TRUE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)

opts_chunk$set(cache     =TRUE, 
               comment   =NA, 
               warning   =FALSE, 
               message   =FALSE, 
               error     =FALSE, 
               echo      =FALSE, 
               eval      =TRUE,
               fig.width =10, 
               fig.height=8,
               fig.path  ="../tex/jk-")

iFig=0
iTab=0
```

```{r init}
library(plyr)
library(dplyr)
library(reshape2)
library(ggplot2)
library(ggplotFL)
library(FLCore)
library(diags)
library(stringr)

dirMy="/home/laurence/Desktop/sea++/xval"
dirDat=file.path(dirMy,"data")
dirVpa=file.path(dirMy,"inputs/vpa")
dirTex=file.path(dirMy,"tex")

m=c(0.3800,0.3000,0.2400,0.2000,0.1800,0.1600,0.1400,0.1300,0.1200,0.1000)

new=readVPA2Box(file.path(dirVpa,"new/bfte2017.c1"),m=m)
```

## Jackknife the  VPA by removing 1 CPUE observation at a time
```{r jack,eval=FALSE}
source('~/Desktop/flr/diags/R/read-VPA2Box-FLIndices.R', echo=TRUE)
source('~/Desktop/flr/diags/R/io.VPA2BoxV2.R', echo=TRUE)
source(file.path(dirMy,'R/jackknife-vpa2box.R'))

press=jackknife.vpa2box(file.path(dirVpa,"new/bfte2017.c1"),m=m)

save(press,file=file.path(dirDat,"press.RData"),compress="xz")
```

Returns a list with `FLStocks` and a `data.frame`, the `FLStocks` contains in the first element the fit to all the data and in the second element an FLStock with `iters` for each deleted CPUE observation. The `data.frame` contains the predicted CPUE values from each iteration of the jackknife.
